name: ci

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, labeled, unlabeled, synchronize ]

jobs:
  format-community-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2
      - name: Version
        run: flutter doctor -v
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - name: Format
        run: melos format --output none --set-exit-if-changed
  analysis-community-charts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2
      - name: Version
        run: flutter doctor -v
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - name: Linter
        run: melos analyze
        # TODO: migrate tests to null-safety
#  test-community-charts-common:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3.1.0
#      - uses: actions/setup-java@v3.6.0
#        with:
#          java-version: 11
#          distribution: temurin
#      - uses: subosito/flutter-action@v2.8.0
#        with:
#          cache: true
#      - name: Tests
#        run: flutter test
#        working-directory: ${{ github.workspace }}/community_charts_common
  test-community-charts-flutter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-java@v3.6.0
        with:
          java-version: 11
          distribution: temurin
      - uses: subosito/flutter-action@v2.8.0
        with:
          cache: true
      - name: Tests
        run: flutter test
        working-directory: ${{ github.workspace }}/community_charts_flutter
